name: GetTrackers

on:
  push:
    branches: [main]
    tags:
      - '*'
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
      - name: cache log
        id: cache-log
        uses: actions/cache@v3
        with:
          path: log
          key: bot-logs
      - name: Run pip install wget
        run: pip install wget
      - name: Run python PyTrackers.py
        run: |
          python PyTrackers.py
        working-directory: ./main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
